### ISSUE TITLE
Condense into static style.json

### ISSUE THREAD

**Issue by wipfli** [ZeLonewolf/maplibre-shield-rotation-sample#4]
I understand that a long style.json file can be intimidating and hard to update consistently. However, for the particular use case of shield rotation I would find a pre-generated style.json file easier to parse by a human.

Can we condense the result of the javascript files into a static style.json file?

**Comment by wipfli** [comment]
Actually that is super easy: I make a pull request. Give me a sec.

**Comment by wipfli** [comment]
`JSON.stringify(style)` from the console...

**Comment by ZeLonewolf** [comment]
Fixed by #5
