### ISSUE TITLE
MapTiler shields

### ISSUE THREAD

**Issue by wipfli** [ZeLonewolf/maplibre-shield-rotation-sample#9]
MapTiler has correctly rotated shields:

![image](https://user-images.githubusercontent.com/53421382/146035213-b92b5a66-3e20-440f-8606-624e88308c7c.png)

**Comment by wipfli** [comment]
I would like to investigate how they do it.

**Comment by ZeLonewolf** [comment]
Those are only single shields.  MapTiler is unable to handle concurrent shields, which is the specific issue that I'm trying to address.  When a road is part of more than one route, we need to be able to display all concurrent routes (up to 6, which will be supported by OpenMapTiles 3.13)

Additional discussion is here:
* ZeLonewolf/openstreetmap-americana#6
* maplibre/maplibre-gl-js#188

In short, that implementation currently uses symbols, which only allow a single symbol to be applied for a feature.  In order to get a linear representation, a formatted expression is needed where you can insert a sequence of images to be displayed linearly across a line.  That is why I noted in #8 that the example really needs at least two symbols, not just one.

The current implementation at https://zelonewolf.github.io/openstreetmap-americana/ does already have some shields, but it's still single shields, and shields for concurrencies (2nd, 3rd, etc routes) are not displayed.

**Comment by wipfli** [comment]
We use their style in the docs repo. The style is available at https://api.maptiler.com/maps/streets/style.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL

```json
{
            "id": "highway-shield",
            "type": "symbol",
            "paint": {
                "text-color": "rgba(37, 36, 36, 1)"
            },
            "filter": [
                "all",
                [
                    "<=",
                    "ref_length",
                    6
                ],
                [
                    "==",
                    "$type",
                    "LineString"
                ],
                [
                    "!in",
                    "network",
                    "us-interstate",
                    "us-highway",
                    "us-state"
                ]
            ],
            "layout": {
                "icon-size": 1,
                "text-font": [
                    "Noto Sans Regular"
                ],
                "text-size": 10,
                "icon-image": "road_{ref_length}",
                "text-field": "{ref}",
                "symbol-spacing": 200,
                "symbol-placement": {
                    "base": 1,
                    "stops": [
                        [
                            10,
                            "point"
                        ],
                        [
                            11,
                            "line"
                        ]
                    ]
                },
                "symbol-avoid-edges": true,
                "icon-rotation-alignment": "viewport",
                "text-rotation-alignment": "viewport"
            },
            "source": "openmaptiles",
            "minzoom": 8,
            "source-layer": "transportation_name"
        },
```

**Comment by wipfli** [comment]
Is `icon-rotation-alignment` the thing we are looking for?

**Comment by ZeLonewolf** [comment]
The `icon-rotation-alignment` property will only rotate a symbol - it will not rotate images that are inside of formatted expressions.  I am using that property now in openstreetmap-americana, but it only works with single symbols.

**Comment by wipfli** [comment]
![image](https://user-images.githubusercontent.com/53421382/146037484-ec3bc620-52f0-4127-9389-2bc2ee630f31.png)

**Comment by wipfli** [comment]
This example here uses `text-rotation-alignment`

**Comment by wipfli** [comment]
#10

**Comment by wipfli** [comment]
I guess this here is not exactly what you suggest in https://github.com/maplibre/maplibre-gl-js/issues/188#issuecomment-870490487

**Comment by ZeLonewolf** [comment]
It's not _terrible_ for two shields, but it's completely unworkable for six shields (yay USA).

**Comment by ZeLonewolf** [comment]
So far the only map of any kind that I've seen that properly handles upright shields arranged linearly is Apple Maps.  There's no reason why mapLibre shouldn't also be able to render symbology in that way.  A cluster of shields ("grouped shields") arranged in a grid of no more than two symbols wide is a less-desirable but workable solution.  However, the linear arrangement is really the ideal render.

**Comment by wipfli** [comment]
Cool. I slowly start understanding what we need. Can you share a location where the apple map handles road concurrency well? I have been browsing around Indianapolis but don't see grouped shields.

**Comment by ZeLonewolf** [comment]
I have a screenshot in https://github.com/maplibre/maplibre-gl-js/issues/188#issuecomment-870490487 that someone with an iPhone obtained for me.  It appears to be in Churchill, PA.  Unfortunately, I don't have access to an Apple device.

**Comment by wipfli** [comment]
Me neither. But it is not a problem. I understand what we need.
